Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true  
   
### gitlab vm ###
  config.vm.define "gitlab" do |gitlab|
    gitlab.vm.box = "ubuntu/bionic64"
    gitlab.vm.hostname = "gitlab"
    gitlab.vm.network "private_network", ip: "192.168.56.21"
    gitlab.vm.provision "shell", path: "provision/add_to_domain.sh" 
    gitlab.vm.provision "shell", path: "provision/gitlab.sh"
    gitlab.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.name = "gitlab"
    end
    end
  
end
