Vagrant.configure("2") do |config|
  
  config.vm.provider "virtualbox" do |vb|
   vb.memory = "4096"
   vb.name = "Gitlab"
   end
  
 
### gitlab vm ###
  config.vm.define "gitlab" do |g|
    g.vm.box = "debian/bullseye64"
    g.vm.network "private_network", ip: "192.168.56.6"
    g.vm.provision "shell", path: "provision/initialize.sh"
    g.vm.provision "shell", reboot: true
    g.vm.provision "shell", path: "provision/add_to_domain.sh" 
   # g.vm.provision "shell", path: "provision/gitlab.sh"
    g.vm.provision "shell", reboot: true
    g.vm.provision "shell", path: "provision/install_node_exporter.sh"
    g.vm.provision "shell", path: "provision/puppetnode_setup.sh"
    g.vm.provision "shell", path: "provision/gitlab.sh"
    end
  
end
