Vagrant.configure("2") do |config|
  
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true  
   
### gitlab vm ###
  config.vm.define "testbox" do |t|
    t.vm.box = "ubuntu/bionic64"
    t.vm.network "private_network", ip: "192.168.56.88"
    t.vm.provision "shell", path: "provision/update.sh" 
    t.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.name = "gitlab"
    end
    end
  
end
