Vagrant.configure("2") do |config|

config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
    
config.winrm.transport = :plaintext
config.winrm.basic_auth_only = true 
  
### prometheus and grafana vm ###
config.vm.define "prom" do |p|
    p.vm.box = "debian/bullseye64"
    p.vm.network "private_network", ip: "192.168.56.4"
    p.vm.provision "shell", path: "provision/initialize.sh"
    p.vm.provision "shell", reboot: true
    p.vm.provision "shell", path: "provision/add_to_domain.sh"
    p.vm.provision "shell", path: "provision/prometheus_grafana.sh"
    p.vm.provision "shell", reboot: true
    end

end 
