Vagrant.configure("2") do |config|
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
    config.winrm.transport = :plaintext
    config.winrm.basic_auth_only = true
  config.vm.define "dc" do |dc|
    dc.vm.guest = :windows
    dc.vm.communicator = "winrm"
    dc.vm.boot_timeout = 600
    dc.vm.graceful_halt_timeout = 600
    dc.winrm.retry_limit = 30
    dc.winrm.retry_delay = 10
    dc.vm.box = "StefanScherer/windows_2019"
    dc.vm.hostname = "a4ldc01"
    dc.vm.network "private_network", ip: "192.168.56.2"
    dc.vm.network :forwarded_port, guest: 3389, host: 23389, id: "msrdp"
    dc.vm.network :forwarded_port, guest: 5985, host: 25985, id: "winrm"
    dc.vm.provision "shell", privileged: "true", path: "provision/setupdc.ps1"
    dc.vm.provision "shell", reboot: true
    dc.vm.provision "shell", privileged: "true", path: "provision/ou_setup.ps1"
    dc.vm.provision "shell", reboot: true
  end

  config.vm.define "win_server" do |win_server|
    win_server.vm.guest = :windows
    win_server.vm.communicator = "winrm"
    win_server.vm.boot_timeout = 600
    win_server.vm.graceful_halt_timeout = 600
    win_server.winrm.retry_limit = 30
    win_server.winrm.retry_delay = 10
    win_server.vm.box = "StefanScherer/windows_2019"
    win_server.vm.hostname = "a4l-winnode01"
    win_server.vm.network "private_network", ip: "192.168.56.3"
    win_server.vm.network :forwarded_port, guest: 3389, host: 33389, id: "msrdp"
    win_server.vm.network :forwarded_port, guest: 5985, host: 35985, id: "winrm"
    win_server.vm.provision "shell", privileged: "true", path: "provision/add_to_domain.ps1"
    win_server.vm.provision "shell", reboot: true 
   end
end
