Vagrant.configure("2") do |config|

config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.name = "Jenkins"
    end
    
  
### prometheus and grafana vm ###
config.vm.define "jenkins" do |j|
    j.vm.box = "debian/bullseye64"
    j.vm.network "private_network", ip: "192.168.56.5"
    j.vm.provision "shell", path: "provision/initialize.sh"
    j.vm.provision "shell", reboot: true
    j.vm.provision "shell", path: "provision/add_to_domain.sh"
    j.vm.provision "shell", path: "provision/jenkins_setup.sh"
    j.vm.provision "shell", path: "provision/install_node_exporter.sh"
    j.vm.provision "shell", path: "provision/puppetnode_setup.sh"
    j.vm.provision "shell", reboot: true
    end

end 
