Vagrant.configure("2") do |config|
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true
  
  config.vm.define "dc" do |dc|
    dc.vm.guest = :windows
    dc.vm.communicator = "winrm"
    dc.vm.boot_timeout = 600
    dc.vm.graceful_halt_timeout = 600
    dc.winrm.retry_limit = 30
    dc.winrm.retry_delay = 10
    dc.vm.box = "StefanScherer/windows_2019"
    dc.vm.hostname = "a4ldc01"
    dc.vm.network "private_network", ip: "192.168.56.2"
    dc.vm.network :forwarded_port, guest: 3389, host: 23389, id: "msrdp"
    dc.vm.network :forwarded_port, guest: 5985, host: 25985, id: "winrm"
    dc.vm.provision "shell", privileged: "true", path: "provision/setupdc.ps1"
    dc.vm.provision "shell", reboot: true
    dc.vm.provision "shell", inline: "Start-Sleep -s 60"
    dc.vm.provision "shell", privileged: "true", path: "provision/ou_setup.ps1"
    dc.vm.provision "shell", privileged: "true", path: "provision/install_win_exporter.ps1"
  end

end
