#!/usr/bin/env bash

##Define Repo Path
repo_path='/home/msx10'
#Start vagrant infra

cd $repo_path/devops-vagrant-lab/active_directory/domain_controller
vagrant up
cd $repo_path/devops-vagrant-lab/puppetmaster
vagrant up
cd $repo_path/devops-vagrant-lab/prometheus_grafana
vagrant up
cd $repo_path/devops-vagrant-lab/jenkins
vagrant up
cd $repo_path/devops-vagrant-lab/git
vagrant up
cd $repo_path/devops-vagrant-lab/active_directory/windows_node
vagrant up

