#!/usr/bin/env bash

##Define Repo Path
repo_path='/home/msx10/repo'
#Start vagrant infra

cd $repo_path/devops-vagrant-lab/active_directory/domain_controller
vagrant destroy
cd $repo_path/devops-vagrant-lab/puppetmaster
vagrant destroy
cd $repo_path/devops-vagrant-lab/prometheus_grafana
vagrant destroy
cd $repo_path/devops-vagrant-lab/jenkins
vagrant destroy
cd $repo_path/devops-vagrant-lab/git
vagrant destroy
cd $repo_path/devops-vagrant-lab/active_directory/windows_node
vagrant destroy

