Vagrant.configure("2") do |config|
  
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true  
  
config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.name = "Linux-01"
 
### linux test vm ###
  config.vm.define "linux01" do |t|
    t.vm.box = "debian/bullseye64"
    t.vm.network "private_network", ip: "192.168.56.97"
    t.vm.provision "shell", path: "provision/initialize.sh"
    t.vm.provision "shell", reboot: true 
    t.vm.provision "shell", path: "provision/add_to_domain.sh"
    t.vm.provision "shell", reboot: true
    t.vm.provision "shell", path: "provision/install_node_exporter.sh"
    t.vm.provision "shell", path: "provision/puppetnode_setup.sh"
    end
  
end
